"""ingest run history

Revision ID: 20b29af8df98
Revises: 
Create Date: 2026-08-22 21:18:19.118155

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20b29af8df98'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('bundle', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=True),
    sa.Column('chars', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_run_source', 'ingest_run', ['tenant', 'bundle', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingest_run_source', table_name='ingest_run')
    op.drop_table('ingest_run')
    # ### end Alembic commands ###
